export const APP_LISTING = [
    {
        logo: 'https://cdn.synck.io.vn/favicon.png',
        name: 'Synck Action',
        descriptions: 'Add more event for your workflow',
        isCommingSoon: false,
        linkGuide: '',
        actions: [
            {
                label: 'Start runs manually',
                value: 'start_runs_manually',
            },
            {
                label: 'Recurring schedule',
                value: 'recurring_schedule',
            },
            {
                label: 'Webhooks',
                value: 'webhooks',
            },
            {
                label: 'RSS feed',
                value: 'rss',
            },
        ],
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/google-workspace-logo.svg',
        name: 'Google Workspace',
        descriptions: 'Enhance productivity with Google Workspace integration.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/gmail-logo.svg',
        name: 'Gmail',
        descriptions: 'Automate email sending, scheduling, and inbox management.',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/google-docs-logo-small.svg',
        name: 'Google docs',
        descriptions: 'Automate document creation, editing, and real-time collaboration.',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/google-drive-logo.svg',
        name: 'Google Drive',
        descriptions: 'Automate file storage, access, and sharing securely in the cloud.',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/google-forms-logo-small.svg',
        name: 'Google form',
        descriptions: 'Automate survey creation, response collection, and data analysis.',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/google-sheets-logo-small.svg',
        name: 'Google Sheets',
        descriptions: 'Automate data management, analysis, and real-time collaboration.',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/google-slides-logo-small.svg',
        name: 'Google Slides',
        descriptions: 'Automate presentation creation, collaboration, and sharing.',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/affinity-logo.svg',
        name: 'Affinity',
        descriptions: 'Leverage Affinity to manage your relationships and networks.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/airtable-logo.svg',
        name: 'Airtable',
        descriptions: 'Organize your data and collaborate with Airtable.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/anthropic-logo.svg',
        name: 'Anthropic',
        descriptions: 'Integrate AI capabilities with Anthropic.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/apollo-logo.svg',
        name: 'Apollo',
        descriptions: 'Boost your sales and outreach with Apollo.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/apple-logo.svg',
        name: 'Apple Store',
        descriptions: 'Streamline your Apple app development process.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/asana-logo.svg',
        name: 'Asana',
        descriptions: 'Manage your projects and tasks with Asana.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/ashby-logo.svg',
        name: 'Ashby',
        descriptions: 'Optimize your hiring and recruiting with Ashby.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/assemblyai-logo.svg',
        name: 'AssemblyAI',
        descriptions: 'Implement powerful speech-to-text with AssemblyAI.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/attio-logo.svg',
        name: 'Attio',
        descriptions: 'Manage customer relationships and data with Attio.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/bitly-logo.svg',
        name: 'Bitly',
        descriptions: 'Shorten, share, and track your links with Bitly.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/bloobirds-logo.svg',
        name: 'Bloobirds',
        descriptions: 'Supercharge your sales process with Bloobirds.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/brevo-logo.svg',
        name: 'Brevo',
        descriptions: 'Simplify your email marketing with Brevo.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/calcom-logo.svg',
        name: 'Cal.com',
        descriptions: 'Schedule meetings seamlessly with Cal.com.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/calendly-logo.svg',
        name: 'Calendly',
        descriptions: 'Automate scheduling and appointments with Calendly.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/callrail-logo.svg',
        name: 'Callrail',
        descriptions: 'Track and analyze your calls with Callrail.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/chargebee-logo.svg',
        name: 'Chargebee',
        descriptions: 'Manage your subscriptions and billing with Chargebee.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/clicksend-logo.svg',
        name: 'Clicksend',
        descriptions: 'Send SMS, emails, and more with Clicksend.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/clickup-logo.svg',
        name: 'Clickup',
        descriptions: 'All-in-one productivity platform for teams with Clickup.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/coda-logo.svg',
        name: 'Coda',
        descriptions: 'Create collaborative documents and spreadsheets with Coda.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/convertkit-logo.svg',
        name: 'Convertkit',
        descriptions: 'Grow your audience with Convertkit.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/documint-logo.svg',
        name: 'Documint',
        descriptions: 'Automate document generation with Documint.',
        isCommingSoon: false,
        linkGuide: '',
        actions: [
            {
                label: 'Create document',
                value: 'create_document',
            },
        ],
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/docusign-logo.svg',
        name: 'Docusign',
        descriptions: 'Send and sign documents electronically with Docusign.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/drip-logo.svg',
        name: 'Drip',
        descriptions: 'Automate your email marketing with Drip.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/dropbox-logo.svg',
        name: 'Dropbox',
        descriptions: 'Store and share files with Dropbox.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/facebook-logo.svg',
        name: 'Facebook',
        descriptions: 'Integrate your app with Facebook.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/fibery-logo.svg',
        name: 'Fibery',
        descriptions: 'Manage your projects and knowledge with Fibery.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/fillout-logo.svg',
        name: 'Fillout',
        descriptions: 'Create and manage forms with Fillout.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/front-logo.svg',
        name: 'Front',
        descriptions: 'Collaborate on email and messages with Front.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/github-logo.svg',
        name: 'Github',
        descriptions: 'Manage your code repositories with Github.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/google-ai-studio-logo.svg',
        name: 'Google AI Studio',
        descriptions: 'Integrate AI solutions with Google AI Studio.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/google-play-store-logo.svg',
        name: 'Google Play Store',
        descriptions: 'Manage your app distribution with Google Play Store.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/greenhouse-logo.svg',
        name: 'Greenhouse',
        descriptions: 'Streamline your hiring process with Greenhouse.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/harvest-logo.svg',
        name: 'Harvest',
        descriptions: 'Track time and manage projects with Harvest.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/helpscout-logo.svg',
        name: 'HelpScout',
        descriptions: 'Provide exceptional customer service with HelpScout.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/hubspot-logo.svg',
        name: 'Hubspot',
        descriptions: 'Automate your marketing and sales with Hubspot.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/intercom-logo.svg',
        name: 'Intercom',
        descriptions: 'Communicate with customers in real-time with Intercom.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/atlassian-jira-logo.svg',
        name: 'Jira',
        descriptions: 'Track and manage projects with Jira.',
        isCommingSoon: true,
        linkGuide: '',
        actions: [
            {
                label: 'Add page to database',
                value: 'add_page',
            },
            {
                label: 'Update page',
                value: 'update_page',
            },
            {
                label: 'Create page',
                value: 'create_page',
            },
            {
                label: 'Create or Update page',
                value: 'create_or_update_page',
            },
            {
                label: 'Append to page',
                value: 'append_to_page',
            },
            {
                label: 'Trash page',
                value: 'trash_page',
            },
            {
                label: 'Find page(s)',
                value: 'trash_page',
            },
        ],
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/jotform-logo.svg',
        name: 'Jotform',
        descriptions: 'Create powerful forms and surveys with Jotform.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/lemlist-logo.svg',
        name: 'Lemlist',
        descriptions: 'Personalize your email outreach with Lemlist.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/lever-logo.svg',
        name: 'Lever',
        descriptions: 'Optimize your recruiting with Lever.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/linear-logo.svg',
        name: 'Linear',
        descriptions: 'Streamline issue tracking and project management with Linear.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/loops-logo.svg',
        name: 'Loops',
        descriptions: 'Automate your data workflows with Loops.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/mailchimp-logo.svg',
        name: 'Mailchimp',
        descriptions: 'Create and manage email campaigns with Mailchimp.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/mailjet-logo.svg',
        name: 'Mailjet',
        descriptions: 'Send and track emails with Mailjet.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/microsoft-logo.svg',
        name: 'Microsoft',
        descriptions: 'Integrate with Microsoft products and services.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/monday-logo.svg',
        name: 'Monday',
        descriptions: 'Manage your work and projects with Monday.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/notion-logo.svg',
        name: 'Notion',
        descriptions: 'Organize your work and collaborate with Notion.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/openai-logo.svg',
        name: 'OpenAI',
        descriptions: 'Integrate AI capabilities with OpenAI.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/paddle-logo.svg',
        name: 'Paddle',
        descriptions: 'Manage your subscriptions and billing with Paddle.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/paperform-logo.svg',
        name: 'Paperform',
        descriptions: 'Create and manage forms with Paperform.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/perplexity-logo.svg',
        name: 'Perplexity',
        descriptions: 'Integrate AI-powered solutions with Perplexity.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/pipedrive-logo.svg',
        name: 'Pipedrive',
        descriptions: 'Manage your sales pipeline with Pipedrive.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/posthog-logo.svg',
        name: 'Posthog',
        descriptions: 'Track product analytics with Posthog.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/quickbooks-online-logo.svg',
        name: 'QuickBooks Online',
        descriptions: 'Manage your accounting and finances with QuickBooks Online.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/ringcentral-logo.svg',
        name: 'RingCentral',
        descriptions: 'Streamline your communication with RingCentral.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/salesforce-logo.svg',
        name: 'Salesforce',
        descriptions: 'Manage your customer relationships with Salesforce.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/scrapingbee-logo.svg',
        name: 'ScrapingBee',
        descriptions: 'Automate web scraping with ScrapingBee.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/semrush-logo.svg',
        name: 'Semrush',
        descriptions: 'Optimize your SEO with Semrush.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/signeasy-logo.svg',
        name: 'SignEasy',
        descriptions: 'Sign documents electronically with SignEasy.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/slack-logo.svg',
        name: 'Slack',
        descriptions: 'Collaborate and communicate with Slack.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/smartlead-ai-logo.svg',
        name: 'Smartlead AI',
        descriptions: 'Optimize your lead generation with Smartlead AI.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/smartsuite-logo.svg',
        name: 'SmartSuite',
        descriptions: 'Manage your work and projects with SmartSuite.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/square-logo.svg',
        name: 'Square',
        descriptions: 'Manage your payments with Square.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/stripe-logo.svg',
        name: 'Stripe',
        descriptions: 'Manage your payments and subscriptions with Stripe.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/syften-logo.svg',
        name: 'Syften',
        descriptions: 'Monitor your brand online with Syften.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/things-logo.svg',
        name: 'Things',
        descriptions: 'Organize your tasks and projects with Things.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/todoist-logo.svg',
        name: 'Todoist',
        descriptions: 'Manage your tasks and projects with Todoist.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/trello-logo.svg',
        name: 'Trello',
        descriptions: 'Organize your projects with Trello.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/tremendous-logo.svg',
        name: 'Tremendous',
        descriptions: 'Reward and incentivize with Tremendous.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/typeform-logo.svg',
        name: 'Typeform',
        descriptions: 'Create interactive forms and surveys with Typeform.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/wave-logo.svg',
        name: 'Wave',
        descriptions: 'Manage your accounting and finances with Wave.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/webflow-logo.svg',
        name: 'Webflow',
        descriptions: 'Build and manage your website with Webflow.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/xodo-sign-logo.svg',
        name: 'Xodo Sign',
        descriptions: 'Sign documents electronically with Xodo Sign.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/zendesk-logo.svg',
        name: 'Zendesk',
        descriptions: 'Provide customer support with Zendesk.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/zoom-logo.svg',
        name: 'Zoom',
        descriptions: 'Host video meetings with Zoom.',
        isCommingSoon: true,
        linkGuide: '',
    },
    {
        logo: 'https://cdn.relay.app/app/assets/sources/zoom-events-logo.svg',
        name: 'Zoom Events',
        descriptions: 'Host virtual events with Zoom Events.',
        isCommingSoon: true,
        linkGuide: '',
    },
];
